twitter:

  # Client settings
  # consumer key for twitter api
  #consumer_key: your_consumer_key_here
  # consumer secret for twitter api
  #consumer_secret: your_consumer_secrete_her
  # access token key for twitter api
  #access_token_key: your_access_token_key_here
  # access token secret for twitter api
  #access_token_secret: your_access_token_secret_here

  # The bot will stop when api calls remaining are under
  # min_ratelimit_percent of the max that twitter allows
  min_ratelimit_percent: 10


  # Search for contest settings
  search:

    # Queries to use for searching giveaways.
    # You can set the language for a specific query like this
    # - query
    # - query with language filter:
    #   lang: en
    queries:
      - RT to win
      - Retweet and win
      - Giveaway retweet

    # Will skip all retweeted post until it finds a new one
    # Be ware, that it may use many api calls
    skip_retweeted: false

    # Max tweets that holds the bot in memory to post
    max_queue: 100

    # The maximum quotes that will be recursively search
    # for the original tweet
    max_quote_depth: 20
    # Some tweets are quotes of another tweet
    # This is the mimimum similary between the quote and the post
    min_quote_similarity: 0.5

    #Plugins to filter tweets
    filter:
      # Filter out tweets that have less retweets than `number`
      min_retweets:
        # If this filter method is enabled
        enabled: true
        # If a tweet has less retweets than this number, dont retweet
        number: 20
      # Filter out tweets that contains some criteria
      blacklist:
        # If this filter method is enabled
        enabled: false
        # keywords that if a posts contains would be filtered
        # leave it empty if you want to disable keywords
        keywords: []
        # Filter based on user screen name. Add here the screen names that you want to filter
        # the screen name is the @User name without the @
        users: ["BotSpotterBot"]
    #Plugins to sort tweets
    sort:
      # Give priority to posts that contain some words
      by_keywords:
        # If this sorting method is enabled
        enabled: true
        # Keywords to search
        keywords: ["ps4", "pc"]
      # Give priority to newer posts
      by_age:
        # If this sorting method is enabled
        enabled: true
      # Give priority to posts with more retweets
      by_retweets_count:
        # If this sorting method is enabled
        enabled: true


  # Actions that some giveaways require to enter
  actions:
    # Follow the user that posts the giveaway
    follow:
      # If this action is enabled
      enabled: true
      # Keywords to search in post for follow action
      keywords: ["follow", "follower"]
      # When max_following is reached, will unfollow oldest follows
      max_following: 1950
      # Follow multiple account from a single post
      # Experimental feature, please open issue with example post id if unusual behavior is observed
      multiple: false
    # Favorite the post
    favorite:
      # If this action is enabled
      enabled: true
      # Keywords to search in post for favorite action
      keywords: ["fav", "favorite", "like"]
    #This action allows to tag friends when requested
    # Experimental feature, please open issue with example post id if unusual behavior is observed
    tag_friend:
      # If this action is enabled
      enabled: false
      # Friends usernames to tag. Bot will randomly pick the required number
      # Usually maximum number of required tags is 3, so better define here 3 or more
      friends: ["friend1", "friend2", "friend3"]
      # keywords of tag to serach in post
      tag_keywords: ["tag"]
      # keywords of friend to search in post
      friend_keywords: ["friend", "friends"]
      # keywords of numbers to search in post
      number_keywords:
        1: ["one", "1", "a", "your"]
        2: ["two", "2"]
        3: ["three", "3"]
        4: ["four", "4"]

  # Intervals of bot tasks
  scheduler:
    # How often will search for new posts
    search_interval: 5400
    # How often will retweet
    retweet_interval: 600
    # A random margin from retweet interval to avoid bot detection
    retweet_random_margin: 60
    # Update blocked users list so posts of them are not retweeted
    blocked_users_update_interval: 300
    # How often will delete oldest posts in queue
    clear_queue_interval: 60
    # How often will update the remaining api rate limits
    rate_limit_update_interval: 60
    # How often will check for new mentions
    check_mentions_interval: 600

# Notifiers will notify when somenone mentions the user.(Possible win)
notifiers:
  # Pushbullet notifier
  pushbullet:
    # If the notifier is enabled
    enabled: false
    # Pushbullet api token
    token: my_pushbullet_token
  # Email notifier
  mail:
    # If the notifier is enabled
    enabled: false
    # Email provider smpt server
    host: smtp.provider.com
    # Port
    port: 25
    # Use tls
    tls: false
    # Email username
    username: sender_address@provider.com
    # Email password
    password: my_secure_password
    # Notification recipient
    recipient: sender_address@provider.com


